#!/bin/bash
#This shebang is for synax only. Do not make executable!

export ROOT=$(dirname $0)
export PROG=$(basename $0)
source ${ROOT}/scripts/bch:misc
source ${ROOT}/scripts/bch:dev

source mycmd:

__home   () { echo $(mydts uniq -r MYENV_RSYNC_HOME_DIR); }
__backup () { echo $(seagate_blue_backups 2> /dev/null); }

NULL_bch_seagate () {
    $PROG -h
}

INIT_bch_seagate () {
    mydts -f
    bch:dev:insitu_all
}

USER_bch_seagate_check () {
    echo "home: [$(__home)]"
    echo "backup: [$(__backup)]"
}

USER_bch_seagate_backup () {
    [ ! -d "$(__backup)"  ] && echo backup not attached && exit
    [ ! -d "$(__home)" ] && echo home not defined && exit
    for target in $(bch:misc:listdir $(__home)); do
        echo "[$PROG]: ${target} --> $(__backup)"
        rsync -av --del --exclude .mytags ${target} $(__backup)
    done
}

mycmd:main $0 $*
